include:
  - sysctl.forwarding
  - sysctl.hightraffic
  - network.ip_rules_freifunk
  - gw.rc_local
  - network.interfaces_direct
  - network.interfaces_gre_internal
  - network.br_ffwp
  - batman
  - gw.bird
  - dhcp_server
  - unbound
  - fastd
  - gw.stats
  - gw.respondd
