include:
  - common.telegraf
  - sysctl.forwarding
  - sysctl.hightraffic
  - wireguard
  - bgp.ferm
  - bgp.ip_rules_bgp
  - bgp.rc_local
  - network.interfaces_gre_exit
  - network.interfaces_gre_internal
  - network.interfaces_direct
  - bgp.bird
